[project]
name = "mojo-torch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mojo>=0.25.6.1",
    "numpy>=2.3.4",
    "ruff>=0.14.1",
    "torch>=2.9.0",
]
